name: Deploy Node.js App

on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Package app with npm
      run: |
        curl -sL https://deb.nodesource.com/setup_18.x | sudo -E bash -
        sudo apt-get install -y nodejs
        npm install
        npm run build
    - name: Copy files to server
      uses: appleboy/scp-action@master
      with:
        host: ${{secrets.HOST}}
        username: ${{secrets.USER}}
        password: ${{ secrets.PWD }}
        source: dist/
        target: /usr/share/nginx/html/dist
    
